version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - db

  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://localhost:8080/api

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ducklab
      MYSQL_USER: ducklab
      MYSQL_PASSWORD: ducklab
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
