export * from "./Position";
export * from "./Size";
export * from "./Color";
export * from "./Rotation";
export * from "./Font";
export * from "./Name";
export * from "./LineWidth";
export * from "./Img";
export * from "./Scale";
export * from "./Polygon";
// const components =  import.meta.glob("./*", { eager: true });
// export * from components;
